# Description: This file is used to draw bounding boxes on the images and display them to the user. 
# It is used to test the accuracy of the bounding boxes generated by the dataset converter.
# This is a test file

import cv2
from pathlib import Path

# Where the Yolo Dataset is stored
YOLO_DIR = Path('/home/eesh/forge/YOLO_DATASET/DATASETv4')

SUBFOLDER = 'train'
# The directory containing the images and labels
IMAGE_DIR = YOLO_DIR / SUBFOLDER / 'images'
LABEL_DIR = YOLO_DIR / SUBFOLDER / 'labels'

for img_file in IMAGE_DIR.glob("*.png"):
    img = cv2.imread(str(img_file))
    raw_image = img.copy()
    label_file = LABEL_DIR / (img_file.stem + ".txt")
    with open(label_file, 'r') as f:
        for line in f:
            if line[0] == "(":
                continue
                line = line.strip()[1:-1].split(", ")[:-1]
                cls, x1, y1, x2, y2 = map(int, line)
                print(img_file.stem, cls, x1, y1, x2, y2)
                img = cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            else:
                line = line.strip().split()
                # format class x_center y_center width height
                cls, x, y, w, h = line
                x, y, w, h = map(float, (x, y, w, h))
                x1 = int((x - w/2) * img.shape[1])
                y1 = int((y - h/2) * img.shape[0])
                x2 = int((x + w/2) * img.shape[1])
                y2 = int((y + h/2) * img.shape[0])
                print(img_file.stem, cls, x1, y1, x2, y2)
                img = cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
    cv2.imshow('bbox_image', img)
    cv2.imshow('raw_image', raw_image)
    if cv2.waitKey(0) & 0xFF == ord('q'):
        break
cv2.destroyAllWindows()
    

